### ISSUE TITLE
RTC Set Date Time

### ISSUE THREAD

**Issue by Jxid** [Makuna/Rtc#101]
Hi
I am trying your library but since now i can't set the tame and date from my PC.
I have tried 

`  RtcDateTime compiled = RtcDateTime(__DATE__, __TIME__);
  Rtc.SetDateTime(compiled);
`
but i can not set the time and date.
What is the right way to set it from my PC or even manual?
Thank you,
Yannis.

**Comment by Makuna** [comment]
If you follow the instructions, these sorts of questions should be asked on the gitter channel and not entered as an issue (bug).

https://gitter.im/Makuna/Rtc
