### ISSUE TITLE
problema libreria ds3231 ,rtc.h  error: no such file or directory con ide version 1.8.1

### ISSUE THREAD

**Issue by crisstiano1** [Makuna/Rtc#103]
**NOTE:  If you are seeking help or have questions, this is NOT the place to do it.**  For questions and support, jump on Gitter and ask away.  
[![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/Makuna/Rtc?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Development environment (please complete the following information):**
 - OS: [e.g. Win10]
 - Build Environment [e.g. Arduino IDE v.1.8.10]
 - Board target [e.g.  AVR Mege 2560, v 1.10.31 ] - you will need to check the board manager for this.
 - Library version [e.g. v2.3.4] - you will need to check the library manager for this.  If you used github to clone it, mention this and include the reference.

**Minimal Sketch that reproduced the problem:**
If an example will demonstrate the problem, list which example you used.
If its your sketch, take the time to remove unneeded parts and minimize it to the smallest sketch that reproduces the problem.  Then include the sketch here using `code` markup.  Start with a line with three single left quotes and then end with a line with three single left quotes. 

**Additional context**

**Comment by Makuna** [comment]
I can't do anything with this.  Please follow the instructions to provide the needed information to reproduce the issue.
