### ISSUE TITLE
SetTime from Serial window

### ISSUE THREAD

**Issue by gpalmia** [Makuna/Rtc#112]
I use your library for the RTC ds3231 with Arduino or with Esp32.
It works very well but I can't set the date and time using the serial window (manually).
Do you have any suggestions?

**Comment by Makuna** [comment]
When you created this issue, did you read the templates?

The "Issues" area is NOT for general questions, it is for a "found bug" or "feature request".  To ask general questions use Gitter (see Wiki or Readme for a link).
