### ISSUE TITLE
Compilation error: 'RtcDateTime' does not name a type; did you mean 'st_atime'?

### ISSUE THREAD

**Issue by g1ra** [Makuna/Rtc#202]
Your DS3231 example is working well , however when I'm trying to copy paste the code in my project , I'm getting error 
**Compilation error: 'RtcDateTime' does not name a type; did you mean 'st_atime'?**

ARDUINO IDE 2.2.1

`/home/bob/Arduino/ESP32_S2_Entrance_GPS_Radar_Light_v2/ESP32_S2_Entrance_GPS_Radar_Light_v2.ino:627:26: error: 'RtcDateTime' does not name a type; did you mean 'st_atime'?
 void printDateTime(const RtcDateTime& dt)
                          ^~~~~~~~~~~
                          st_atime
`
void printDateTime(const RtcDateTime& dt)
{
    char datestring[26];

    snprintf_P(datestring, 
            countof(datestring),
            PSTR("%02u/%02u/%04u %02u:%02u:%02u"),
            dt.Month(),
            dt.Day(),
            dt.Year(),
            dt.Hour(),
            dt.Minute(),
            dt.Second() );
    PR(datestring);
}

**Comment by g1ra** [comment]
<script src="https://gist.github.com/g1ra/d8fb2eae4e125098fe222ef9df3f790e.js"></script>

**Comment by g1ra** [comment]
<script src="https://gist.github.com/g1ra/d8fb2eae4e125098fe222ef9df3f790e.js"></script>

**Comment by Makuna** [comment]
Did you read the solution that was mentioned?  

Move all the includes to the top of the INO file.  Having code above the includes causes the IDE to do weird things it states.

**Comment by g1ra** [comment]
that helped but I really don't like your library . I'm only using because a support of Twowire . 
It takes a long time to get anything up and running . Took me long time even a simple example to move into my project until I understood the error printing function . I'm running into weird errors normally I don't encounter because you don't have 
rtc.getEpoch function . I have to figure out how to get epoch out of  RtcDateTime .
In my opinion RtcDateTime is a huge bum . I don't want to use it .

**Comment by g1ra** [comment]
for example I have this function always working . but not with your library : 

 
```c++
String dateTimeMilDS3231()
{
  char mname[DATE_STRING_SHORT + 1];
  char dname[DATE_STRING_SHORT + 1];
  dname[DATE_STRING_SHORT] = '\0';
   
  char buf[64];
  
#if defined(ESP32)
    long unsigned int epoch;
#else
    uint32_t epoch;
#endif
    
  RtcDateTime now2 = rtc.GetDateTime();
  epoch = now2.Unix32Time();
  PRLN(epoch);
  DateTime dt0(epoch);
  PRLN(epoch);

  // Testing here what breaks , I got a weird datetime . : 
  strncpy_P(dname, &(dayNames_P[dt0.dayOfTheWeek() * DATE_STRING_SHORT]), DATE_STRING_SHORT);
  PRLN(epoch);
  time_t t = dt0.unixtime();
  struct tm *lt = localtime(&t);
  char str[32];
  strftime(str, sizeof(str), "%Y.%m.%d:%H.%M.%S", lt); 
  Serial.println(str);

//  snprintf(buf, sizeof(buf), "20%02d-%d-%02d %02d:%02d:%02d %s",
//           dt0.tm_mday, dt.tm_year, dt.tm_mon, dt.tm_hour, dt.tm_min, dt.tm_sec, dname);#
  snprintf(buf, sizeof(buf), "%d-%02d-%02d %s %02d:%02d:%02d %s",
           dt0.year(), dt0.month(), dt0.day(), dname, dt0.hour(), dt0.minute(), dt0.second());           
//  snprintf(buf, sizeof(buf), "20%02d-%d-%02d %02d:%02d:%02d %s",
//           dt0.day(), dt0.year(), dt0.month(), dt0.hour(), dt0.minute(), dt0.second(), dt0.dayOfTheWeek() );           
  //String dtr = String(dt.dayWeek) +" "+String(dt.dayMonth)+"-"+String(dt.year)+" "+String(dt.month)+":"+String(dt.hour)+":"+String(dt.minute)+":"+String(dt.second);
  PRLN(epoch);

  return String(buf);
}

```

**Comment by g1ra** [comment]
sorry I had to delete %s from snprintf then worked. 
I appreciate your effort to provide different epoch'es , bit confusing though it would need documentation or example for RtcDateTime
