### ISSUE TITLE
Error compiling after Update

### ISSUE THREAD

**Issue by rainerfritz** [Makuna/Rtc#24]
Hi !
Use your library on an ESP8266 and get now following error:
invalid use of template-name 'RtcDS3231' without an argument list
When generating the object with:
RtcDS3231 Rtc;
thx
Rainer

**Comment by Makuna** [comment]
How you construct the time object has changed between version 1 and version 2 (the latest).

Please see Wiki pages [here](https://github.com/Makuna/Rtc/wiki/RtcDS3231-object) and you will see only a small change is needed and it should work.

old way
```
RtcDS3231 Rtc();
```

new way
```
RtcDS3231<TwoWire> Rtc(Wire);
```

**Comment by rainerfritz** [comment]
THX for the info works fine !!

**Comment by Makuna** [comment]
Created a FAQ in the wiki for this.
