### ISSUE TITLE
Use hour minute in variable

### ISSUE THREAD

**Issue by maxholgasson** [Makuna/Rtc#27]
Hi,

how can I use the time and store hour and minute in variables?
In the DS3231 Simple - Example is only a Serial print

Thanks

**Comment by Makuna** [comment]
This is less an issue and more a simple question, better suited for the gitter channel.
[![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/Makuna/Rtc?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

Just use the access members for hour and minute from the RtcDateTime object like the example does to print it, but just assign it to a variable...
```
RtcDateTime now = Rtc.GetDateTime();
uint8_t hour = now.Hour();
uint8_t minute = now.Minute();
```

**Comment by maxholgasson** [comment]
Thanks a lot, I will try this.  What is the gitter channel?

**Comment by Makuna** [comment]
Follow the link I included (the button).  Gitter is a chat system tied to github projects.  Great for questions and simple issues to reduce "noise" in the GitHub issues area.
