### ISSUE TITLE
Errores compilacion

### ISSUE THREAD

**Issue by agcII** [Makuna/Rtc#29]
Arduino:1.8.0 (Windows 10), Tarjeta:"Arduino Due (Programming Port)"

In file included from C:\Users\JuanJo\Documents\Arduino\DS3231_Simple\DS3231_Simple.ino\DS3231_Simple.ino.ino:24:0:

C:\Users\JuanJo\Documents\Arduino\libraries\Rtc_by_Makuna\src/RtcDS3231.h:43:48: error: '_BV' was not declared in this scope

 const uint8_t DS3231_AIEMASK = (_BV(DS3231_A1IE) | _BV(DS3231_A2IE));

                                                ^

C:\Users\JuanJo\Documents\Arduino\libraries\Rtc_by_Makuna\src/RtcDS3231.h:43:67: error: '_BV' was not declared in this scope

 const uint8_t DS3231_AIEMASK = (_BV(DS3231_A1IE) | _BV(DS3231_A2IE));

                                                                   ^

C:\Users\JuanJo\Documents\Arduino\libraries\Rtc_by_Makuna\src/RtcDS3231.h:44:46: error: '_BV' was not declared in this scope

 const uint8_t DS3231_RSMASK = (_BV(DS3231_RS1) | _BV(DS3231_RS2));

                                              ^

C:\Users\JuanJo\Documents\Arduino\libraries\Rtc_by_Makuna\src/RtcDS3231.h:44:64: error: '_BV' was not declared in this scope

 const uint8_t DS3231_RSMASK = (_BV(DS3231_RS1) | _BV(DS3231_RS2));

                                                                ^

C:\Users\JuanJo\Documents\Arduino\libraries\Rtc_by_Makuna\src/RtcDS3231.h:52:47: error: '_BV' was not declared in this scope

 const uint8_t DS3231_AIFMASK = (_BV(DS3231_A1F) | _BV(DS3231_A2F));

                                               ^

C:\Users\JuanJo\Documents\Arduino\libraries\Rtc_by_Makuna\src/RtcDS3231.h:52:65: error: '_BV' was not declared in this scope

 const uint8_t DS3231_AIFMASK = (_BV(DS3231_A1F) | _BV(DS3231_A2F));

                                                                 ^

C:\Users\JuanJo\Documents\Arduino\libraries\Rtc_by_Makuna\src/RtcDS3231.h: In member function 'bool RtcDS3231<T_WIRE_METHOD>::IsDateTimeValid()':

C:\Users\JuanJo\Documents\Arduino\libraries\Rtc_by_Makuna\src/RtcDS3231.h:239:41: error: there are no arguments to '_BV' that depend on a template parameter, so a declaration of '_BV' must be available [-fpermissive]

         return !(status & _BV(DS3231_OSF));

                                         ^

C:\Users\JuanJo\Documents\Arduino\libraries\Rtc_by_Makuna\src/RtcDS3231.h:239:41: note: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)

C:\Users\JuanJo\Documents\Arduino\libraries\Rtc_by_Makuna\src/RtcDS3231.h: In member function 'bool RtcDS3231<T_WIRE_METHOD>::GetIsRunning()':

C:\Users\JuanJo\Documents\Arduino\libraries\Rtc_by_Makuna\src/RtcDS3231.h:245:40: error: there are no arguments to '_BV' that depend on a template parameter, so a declaration of '_BV' must be available [-fpermissive]

         return !(creg & _BV(DS3231_EOSC));

                                        ^

C:\Users\JuanJo\Documents\Arduino\libraries\Rtc_by_Makuna\src/RtcDS3231.h: In member function 'void RtcDS3231<T_WIRE_METHOD>::SetIsRunning(bool)':

C:\Users\JuanJo\Documents\Arduino\libraries\Rtc_by_Makuna\src/RtcDS3231.h:252:37: error: there are no arguments to '_BV' that depend on a template parameter, so a declaration of '_BV' must be available [-fpermissive]

             creg &= ~_BV(DS3231_EOSC);

                                     ^

C:\Users\JuanJo\Documents\Arduino\libraries\Rtc_by_Makuna\src/RtcDS3231.h:256:36: error: there are no arguments to '_BV' that depend on a template parameter, so a declaration of '_BV' must be available [-fpermissive]

             creg |= _BV(DS3231_EOSC);

                                    ^

C:\Users\JuanJo\Documents\Arduino\libraries\Rtc_by_Makuna\src/RtcDS3231.h: In member function 'void RtcDS3231<T_WIRE_METHOD>::SetDateTime(const RtcDateTime&)':

C:\Users\JuanJo\Documents\Arduino\libraries\Rtc_by_Makuna\src/RtcDS3231.h:265:34: error: there are no arguments to '_BV' that depend on a template parameter, so a declaration of '_BV' must be available [-fpermissive]

         status &= ~_BV(DS3231_OSF); // clear the flag

                                  ^

C:\Users\JuanJo\Documents\Arduino\libraries\Rtc_by_Makuna\src/RtcDS3231.h:282:32: error: there are no arguments to '_BV' that depend on a template parameter, so a declaration of '_BV' must be available [-fpermissive]

             centuryFlag = _BV(7);

                                ^

C:\Users\JuanJo\Documents\Arduino\libraries\Rtc_by_Makuna\src/RtcDS3231.h: In member function 'RtcDateTime RtcDS3231<T_WIRE_METHOD>::GetDateTime()':

C:\Users\JuanJo\Documents\Arduino\libraries\Rtc_by_Makuna\src/RtcDS3231.h:309:29: error: there are no arguments to '_BV' that depend on a template parameter, so a declaration of '_BV' must be available [-fpermissive]

         if (monthRaw & _BV(7)) // century wrap flag

                             ^

C:\Users\JuanJo\Documents\Arduino\libraries\Rtc_by_Makuna\src/RtcDS3231.h: In member function 'void RtcDS3231<T_WIRE_METHOD>::Enable32kHzPin(bool)':

C:\Users\JuanJo\Documents\Arduino\libraries\Rtc_by_Makuna\src/RtcDS3231.h:340:39: error: there are no arguments to '_BV' that depend on a template parameter, so a declaration of '_BV' must be available [-fpermissive]

             sreg |= _BV(DS3231_EN32KHZ);

                                       ^

C:\Users\JuanJo\Documents\Arduino\libraries\Rtc_by_Makuna\src/RtcDS3231.h:344:40: error: there are no arguments to '_BV' that depend on a template parameter, so a declaration of '_BV' must be available [-fpermissive]

             sreg &= ~_BV(DS3231_EN32KHZ);

                                        ^

C:\Users\JuanJo\Documents\Arduino\libraries\Rtc_by_Makuna\src/RtcDS3231.h: In member function 'void RtcDS3231<T_WIRE_METHOD>::SetSquareWavePin(DS3231SquareWavePinMode)':

C:\Users\JuanJo\Documents\Arduino\libraries\Rtc_by_Makuna\src/RtcDS3231.h:354:52: error: there are no arguments to '_BV' that depend on a template parameter, so a declaration of '_BV' must be available [-fpermissive]

         creg &= ~(DS3231_AIEMASK | _BV(DS3231_BBSQW));

                                                    ^

C:\Users\JuanJo\Documents\Arduino\libraries\Rtc_by_Makuna\src/RtcDS3231.h:355:33: error: there are no arguments to '_BV' that depend on a template parameter, so a declaration of '_BV' must be available [-fpermissive]

         creg |= _BV(DS3231_INTCN);  // set INTCN to disables SQW

                                 ^

C:\Users\JuanJo\Documents\Arduino\libraries\Rtc_by_Makuna\src/RtcDS3231.h:363:37: error: there are no arguments to '_BV' that depend on a template parameter, so a declaration of '_BV' must be available [-fpermissive]

             creg |= _BV(DS3231_BBSQW); // set battery backup flag

                                     ^

C:\Users\JuanJo\Documents\Arduino\libraries\Rtc_by_Makuna\src/RtcDS3231.h:364:38: error: there are no arguments to '_BV' that depend on a template parameter, so a declaration of '_BV' must be available [-fpermissive]

             creg &= ~_BV(DS3231_INTCN); // clear INTCN to enable SQW 

                                      ^

C:\Users\JuanJo\Documents\Arduino\libraries\Rtc_by_Makuna\src/RtcDS3231.h:368:38: error: there are no arguments to '_BV' that depend on a template parameter, so a declaration of '_BV' must be available [-fpermissive]

             creg &= ~_BV(DS3231_INTCN); // clear INTCN to enable SQW 

                                      ^

C:\Users\JuanJo\Documents\Arduino\libraries\Rtc_by_Makuna\src/RtcDS3231.h:372:36: error: there are no arguments to '_BV' that depend on a template parameter, so a declaration of '_BV' must be available [-fpermissive]

             creg |= _BV(DS3231_A1IE);

                                    ^

C:\Users\JuanJo\Documents\Arduino\libraries\Rtc_by_Makuna\src/RtcDS3231.h:376:36: error: there are no arguments to '_BV' that depend on a template parameter, so a declaration of '_BV' must be available [-fpermissive]

             creg |= _BV(DS3231_A2IE);

                                    ^

C:\Users\JuanJo\Documents\Arduino\libraries\Rtc_by_Makuna\src/RtcDS3231.h:380:36: error: there are no arguments to '_BV' that depend on a template parameter, so a declaration of '_BV' must be available [-fpermissive]

             creg |= _BV(DS3231_A1IE) | _BV(DS3231_A2IE);

                                    ^

C:\Users\JuanJo\Documents\Arduino\libraries\Rtc_by_Makuna\src/RtcDS3231.h:380:55: error: there are no arguments to '_BV' that depend on a template parameter, so a declaration of '_BV' must be available [-fpermissive]

             creg |= _BV(DS3231_A1IE) | _BV(DS3231_A2IE);

                                                       ^

C:\Users\JuanJo\Documents\Arduino\libraries\Rtc_by_Makuna\src/RtcDS3231.h: In member function 'void RtcDS3231<T_WIRE_METHOD>::ForceTemperatureCompensationUpdate(bool)':

C:\Users\JuanJo\Documents\Arduino\libraries\Rtc_by_Makuna\src/RtcDS3231.h:485:32: error: there are no arguments to '_BV' that depend on a template parameter, so a declaration of '_BV' must be available [-fpermissive]

         creg |= _BV(DS3231_CONV); // Write CONV bit

                                ^

C:\Users\JuanJo\Documents\Arduino\libraries\Rtc_by_Makuna\src/RtcDS3231.h:488:48: error: there are no arguments to '_BV' that depend on a template parameter, so a declaration of '_BV' must be available [-fpermissive]

         while (block && (creg & _BV(DS3231_CONV)) != 0)

                                                ^

C:\Users\JuanJo\Documents\Arduino\DS3231_Simple\DS3231_Simple.ino\DS3231_Simple.ino.ino: At global scope:

DS3231_Simple.ino:25: error: 'RtcDS3231<TwoWire> Rtc' redeclared as different kind of symbol

 RtcDS3231<TwoWire> Rtc(Wire);

                            ^

In file included from C:\Users\JuanJo\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.11\system/CMSIS/Device/ATMEL/sam3xa/include/sam3x8e.h:288:0,

                 from C:\Users\JuanJo\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.11\system/CMSIS/Device/ATMEL/sam3xa/include/sam3xa.h:44,

                 from C:\Users\JuanJo\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.11\system/CMSIS/Device/ATMEL/sam3.h:59,

                 from C:\Users\JuanJo\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.11\system/CMSIS/Device/ATMEL/sam.h:198,

                 from C:\Users\JuanJo\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.11\system/libsam/chip.h:25,

                 from C:\Users\JuanJo\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.11\cores\arduino/Arduino.h:42,

                 from sketch\DS3231_Simple.ino.ino.cpp:1:

C:\Users\JuanJo\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.11\system/CMSIS/Device/ATMEL/sam3xa/include/component/component_rtc.h:56:3: error: previous declaration of 'typedef struct Rtc Rtc'

 } Rtc;

   ^

C:\Users\JuanJo\Documents\Arduino\DS3231_Simple\DS3231_Simple.ino\DS3231_Simple.ino.ino: In function 'void setup()':

DS3231_Simple.ino:38: error: expected unqualified-id before '.' token

     Rtc.Begin();

        ^

DS3231_Simple.ino:48: error: expected primary-expression before '.' token

     if (!Rtc.IsDateTimeValid()) 

             ^

DS3231_Simple.ino:60: error: expected unqualified-id before '.' token

         Rtc.SetDateTime(compiled);

            ^

DS3231_Simple.ino:63: error: expected primary-expression before '.' token

     if (!Rtc.GetIsRunning())

             ^

DS3231_Simple.ino:66: error: expected unqualified-id before '.' token

         Rtc.SetIsRunning(true);

            ^

DS3231_Simple.ino:69: error: expected primary-expression before '.' token

     RtcDateTime now = Rtc.GetDateTime();

                          ^

DS3231_Simple.ino:73: error: expected unqualified-id before '.' token

         Rtc.SetDateTime(compiled);

            ^

DS3231_Simple.ino:86: error: expected unqualified-id before '.' token

     Rtc.Enable32kHzPin(false);

        ^

DS3231_Simple.ino:87: error: expected unqualified-id before '.' token

     Rtc.SetSquareWavePin(DS3231SquareWavePin_ModeNone); 

        ^

C:\Users\JuanJo\Documents\Arduino\DS3231_Simple\DS3231_Simple.ino\DS3231_Simple.ino.ino: In function 'void loop()':

DS3231_Simple.ino:92: error: expected primary-expression before '.' token

     if (!Rtc.IsDateTimeValid()) 

             ^

DS3231_Simple.ino:99: error: expected primary-expression before '.' token

     RtcDateTime now = Rtc.GetDateTime();

                          ^

DS3231_Simple.ino:103: error: expected primary-expression before '.' token

     RtcTemperature temp = Rtc.GetTemperature();

                              ^

Se encontraron múltiples librerías para "RtcDS3231.h"
Usado: C:\Users\JuanJo\Documents\Arduino\libraries\Rtc_by_Makuna
 No usado: C:\Users\JuanJo\Documents\Arduino\libraries\RTCtime
 No usado: C:\Users\JuanJo\Documents\Arduino\libraries\RTCtime
 No usado: C:\Users\JuanJo\Documents\Arduino\libraries\RTCtime
 No usado: C:\Users\JuanJo\Documents\Arduino\libraries\RTCtime
exit status 1
'RtcDS3231<TwoWire> Rtc' redeclared as different kind of symbol

Este reporte podría tener más información con
"Mostrar salida detallada durante la compilación"
opción habilitada en Archivo -> Preferencias.

**Comment by Makuna** [comment]
It seems the _BV (bit vector) macro is not defined for that board anymore.  
In your primary sketch, before including the rtc header define the following...
```
#define _BV(b) (1UL << (b))
#include <RtcDs3231.h> // in your sketch, before this include, include the above
```

**Comment by agcII** [comment]
Yes, it works.
and I need to change.
RtcDS3231<TwoWire> Rtc(Wire);
to
RtcDS3231<TwoWire> Rtc2(Wire);

for redefinition errors.


2017-03-31 19:12 GMT+02:00 Michael Miller <notifications@github.com>:

**Comment by agcII** [comment]
Thanks.

2017-03-31 19:15 GMT+02:00 Juan Jose Cabrero <agcfanatic@gmail.com>:

**Comment by Makuna** [comment]
This will work around the issue for now, I will leave this issue open to track making a permanent fix.

**Comment by Makuna** [comment]
2.0.1 includes the fix
