### ISSUE TITLE
Using memory at RTC1307

### ISSUE THREAD

**Issue by jcmojj** [Makuna/Rtc#33]
I see what you did regarding the memory of the RTC1307 and I have some doubts that I didn't find at the lib or at the wiki.
1) What is the max quantity of address I can save using `Rtc.SetMemory(0, 13);`?
2) What is the limit of recording cycles we can have at the memory? Does this number count for one single address or for the memory all together?
3) DS1307_REG_RAMSTART = 0x08 you used in the lib is the address for anything we want to store at DS1307 EEPROM or it is the memory for part of it and it is possible to use other addresses to reach a bigger EEPROM size?
4) It we can use multiple addresses for multiple EEPROM parts at DS1307, can the life cycles quantity be applied for each address/part of EEPROM in a separate way?
Thank you for the lib!

**Comment by Makuna** [comment]
These are better questions for the gitter channel that an actual issue.  Issues are really bugs or feature requests.

This memory is a feature of the actual DS1307 chip.

The amount of memory is the newish constant DS1307_REG_RAMSIZE.   Which is 55 bytes. The values you pass for the address to set and get memory methods is zero based, so 0 - (DS1307_REG_RAMSIZE - 1) are valid addresses.

You will have to look at the specs of the specific DS1307 you have to how many write cycles its internal memory has.  I don't remember spotting it myself.  There might be even different generations of the chips with different life cycles to them.
