### ISSUE TITLE
Support for 32 and 64 bit unix time(with leap seconds)

### ISSUE THREAD

**Issue by far5893** [Makuna/Rtc#4]
Please add support for epoch time.

**Comment by Makuna** [comment]
My belief is that these are time formats specific to the app and not the real time clock library. But I will look into it.

**Comment by Makuna** [comment]
added support, let me know if you find any bugs.
https://github.com/Makuna/Rtc/commit/a07d34270cb595bbf8b18d33c001b56e84b77fe3
see new methods
```
    uint32_t Epoch32Time() const;
    void InitWithEpoch32Time(uint32_t time);

    uint64_t Epoch64Time() const;
    void InitWithEpoch64Time(uint64_t time);
```
