### ISSUE TITLE
Rpi rtc

### ISSUE THREAD

**Issue by kiralikbeyin** [Makuna/Rtc#40]
Anyone tried to use rpi ds3231?
http://www.dx.com/p/ds3231-raspberry-pi-rtc-board-real-time-clock-module-for-arduino-black-277258#.WZqPw62mOwk

I don't know is it using rechargeable battery but its smaller than other arduino-rtcs.

@Makuna

**Comment by Makuna** [comment]
I haven't.   Its just a ds3231 so it should work.  
I haven't confirmed that this library even works with PI Arduino.

**Comment by kiralikbeyin** [comment]
I tried it with esp and worked. It is really tiny 2cmx2cm 

I read it uses some kind of cr11xx or cr927 and no problem with recharge circuit like normal arduino ds3231 module.
