### ISSUE TITLE
Wemos D1 mini losing time

### ISSUE THREAD

**Issue by kiralikbeyin** [Makuna/Rtc#41]
I am losing time after unplugging Wemos D1 mini cable.

No problem when i set time and restart esp (ESP.restart();) until unplugging cable...

I used same ds3231 device on nodemcu 2.0 amica and unplugged the cable - this works fine no problem!

Any idea?

**Comment by kiralikbeyin** [comment]
https://raspberrypi.stackexchange.com/questions/62735/ds3231-rtc-not-keeping-time-after-shutdown-on-raspberry-pi

I killed the battery! It gives 0.5v

**Comment by Makuna** [comment]
glad you found the answer.  Low batteries seem to be problematic for these chips.  many come with a rechargeable cell; but not all.
