### ISSUE TITLE
Doubts

### ISSUE THREAD

**Issue by JoseCintra** [Makuna/Rtc#48]
Hi! Congratulations for the excellent work!
Only two questions:
1) In the examples, when you use the comparison operators (= or>), the comparison takes into account the date types (date or String?)
2) Any predictions to include methods for EEPROM storage in the ds3231 library? 

Thanks!

**Comment by Makuna** [comment]
Issues are for, well, issues, not questions.  Please use gitter channel for questions.

A:
1)  The comparisons compare the total seconds since 1/1/2000
2) The DS3231 does not have memory to write to or read from.  This feature is not present on that chip.
