### ISSUE TITLE
AsFloat won't compile

### ISSUE THREAD

**Issue by helibosse** [Makuna/Rtc#69]
I have a sketch for Reading the temperature  of an DS3231. It consists of the following lines:

#inlude <RtcDS3231.h>
//Create new RTC module object
RtcDS3231 rtcModule;
void UpdateTemp() {
  // Read temperature
  RtcTemperature rtcTemp = rtcModule.Get.Temperature();
  temp = rtcTemp.AsFloat();
}

The compilation halts with the following remark:

exit status 1
'class RtcTemperature' has no member named 'AsFloat'

Help is highly appreciated
tuvebosse

**Comment by Makuna** [comment]
AsFloat was depreciated and removed.
Use AsFloatDegC or AsFloatDegF.
