### ISSUE TITLE
 Not working when compile for Raspberry2+, please help, thank you 

### ISSUE THREAD

**Issue by Barabba11** [Makuna/Rtc#73]
Hi, I'm compinig with Arduino IDE directly to bin file for my Raspberry3. I have no issues with other I2C libraries, ADC, I/O, etc work fine, but I can't find an RTC lbrary compatible with Raspberry, 
exit status 1, "Errore durante la compilazione per la scheda RaspberryPI B+/2."

I just need to read the clock and store new values.. I;m very sad I can;t find nothing..  strange, I guess it's only a couple of I2C requests tothe device and read the answer, I'm thinking to lead datasheet DS3231 and send I2C commnds manually.
Kindly help me, thank you!

**Comment by Makuna** [comment]
When you opened the issue, you were provided with a template that requests information.  You ignored this.  
Raspberry is not an Arduino platform, any incompatibilities should be addressed by who ever provides your Arduino support for Raspberry.
