### ISSUE TITLE
DS1307_Simple.ino: 'snprintf_P' was not declared in this scope

### ISSUE THREAD

**Issue by Barabba11** [Makuna/Rtc#74]
this sketch seems being compiled for Raspberry but there is a problem with definitions. Maybe I need some library? why it is not already included?
Thank you

**Comment by Makuna** [comment]
When you opened the issue, you were provided with a template that requests information.  You ignored this.  
Raspberry is not an Arduino platform, any incompatibilities should be addressed by who ever provides your Arduino support for Raspberry
