### ISSUE TITLE
DS3231 i2c ESP32

### ISSUE THREAD

**Issue by Albertox0404** [Makuna/Rtc#83]
I need to change the i2c pins to others since another device uses pin 22 to work, how can I change the pins of the ESP2 i2c to work with the DS3231?
I am using the example "DS3231 Simple" that is included with the library
I used this "Wire.begin (16, 17);" in the SETUP as you recommended for the ESP-01, but it does not work and returns erroneous information. This is what it returns:

RTC lost confidence in the DateTime!
85/165/2009 37:165:
-0.25C

Thank you

**Comment by Makuna** [comment]
Please honor the request that questions be asked on gitter channel pointed at in the Readme, the Wiki, and the new issues template. [RTC Library Gitter Channel](https://gitter.im/Makuna/Rtc)

The ISSUES are for tracking known problems with this library, not a place for you to post your issues or ask questions.

What is an ESP2?
Setting the pins as you mentions works.  You have another issue.  Make sure to either use the pins as defined by the hardware for your device, or if it allows, pins not used by other parts of your microcontroller.
More than likely, its your battery.  If you would like to continue and seek help, jump on gitter.
