### ISSUE TITLE
Make DaysSinceFirstOfYear2000 public

### ISSUE THREAD

**Issue by lalo-uy** [Makuna/Rtc#94]
Days calculation may benefit using totalDays as in DaysSinceFirstOfYear2000, instead of having to divide totalSeconds by 3600*24, that has been just multiplied by inside the function.
Hope do not have memory footprint impact.

Thanks for very good job.

**Comment by Makuna** [comment]
https://github.com/Makuna/Rtc/pull/95

**Comment by Makuna** [comment]
v2.3.4
