### ISSUE TITLE
Interrupt on uneven time events, e.g. after 5 minutes, 5 hours, etc.

### ISSUE THREAD

**Issue by mbobinger** [Makuna/Rtc#97]
Dear Makuna,

Thank you for providing us with such a great library. I have been using it nicely on my ATMega328P to call an interrupt service routine each minute using following code:
[code]    DS3231AlarmTwo alarm2(
            0,
            0,
            0, 
            DS3231AlarmTwoControl_OncePerMinute);
    Rtc2.SetAlarmTwo(alarm2);[/code]

To reduce the power consumption further, I'd like to go for an interrupt each 5 minutes. Is that possible to realize with your library?
In that example, it works:
https://forum.arduino.cc/index.php?topic=460850.0

Best and thank you. Please tell me if it is better to post it on gitter.
Marco

**Comment by Makuna** [comment]
The "issues" area is not the place to ask questions.  Please use the Gitter channel (links in the readme and wiki) to ask questions.

It can be done, just not with a simple flag.
