### ISSUE TITLE
Crash in Arduino 1.8.9 with alarm example (ISR not in IRAM!) on ESP8266

### ISSUE THREAD

**Issue by pilnikov** [Makuna/Rtc#98]
Hello.
When i try using alarm example (with IRQ), my esp8266 is crashed with message "ISR not in IRAM!"
I was able to resolve this by adding
` ICACHE_RAM_ATTR` in
`void InteruptServiceRoutine()` declarations
To become so
`void ICACHE_RAM_ATTR InteruptServiceRoutine()`

**Comment by Makuna** [comment]
This is a very specific nuance to programming Esp8266 and Esp32 with no general solution within the context of Arduino to manage it.

How did you come to find the solution?

**Comment by pilnikov** [comment]
https://github.com/esp8266/Arduino/issues/6127

**Comment by pilnikov** [comment]
The problem appeared along with the new (1.8.9) version of the Arduino. In 1.8.5 everything was fine

**Comment by Makuna** [comment]
https://groups.google.com/a/arduino.cc/forum/#!topic/developers/56VPC9t2MPc

**Comment by pilnikov** [comment]
Maybee add a comment about .... ?

**Comment by Makuna** [comment]
https://github.com/Makuna/Rtc/pull/102
I just added my own cross platform method attribute, and updated the examples

**Comment by Makuna** [comment]
v2.3.4
